### ISSUE TITLE
segfault when starting tui with 'q' in input buffer

### ISSUE THREAD

**Issue by Tmplt** [Tmplt/bookwyrm#50]
Reproducable via
```bash
$ src/bookwyrm -t 'some title' <<< q
```

**Comment by Tmplt** [comment]
From the stacktrace it seems like the Python threads are being killed to quickly, or something the like.
```
#0  0x00007ffff772d3d4 in PyObject_GetAttrString () from /nix/store/lp7x6ziq5b2zihgad0i8a28xxvz5vnrr-python3-3.6.4/lib/libpython3.6m.so.1.0
#1  0x0000000000422e3d in pybind11::getattr (name=<optimized out>, obj=...) at /home/tmplt/code/bookwyrm/lib/pybind11/include/pybind11/pytypes.h:366
#2  pybind11::detail::accessor_policies::str_attr::get (key=<optimized out>, obj=...) at /home/tmplt/code/bookwyrm/lib/pybind11/include/pybind11/pytypes.h:489
#3  pybind11::detail::accessor<pybind11::detail::accessor_policies::str_attr>::get_cache (this=this@entry=0x7fffe7c5fe20) at /home/tmplt/code/bookwyrm/lib/pybind11/include/pybind11/pytypes.h:470
#4  0x000000000045c4b2 in pybind11::detail::accessor<pybind11::detail::accessor_policies::str_attr>::ptr (this=<optimized out>) at /home/tmplt/code/bookwyrm/lib/pybind11/include/pybind11/pytypes.h:465
#5  pybind11::detail::object_api<pybind11::detail::accessor<pybind11::detail::accessor_policies::str_attr> >::operator()<(pybind11::return_value_policy)1, bookwyrm::core::item const&, bookwyrm::core::plugin_handler* const&> (this=this@entry=0x7fffe7c5fe20, 
    args#0=..., args#1=@0xb25e70: 0x7fffffff8800) at /home/tmplt/code/bookwyrm/lib/pybind11/include/pybind11/cast.h:2046
#6  0x0000000000459ce2 in bookwyrm::core::plugin_handler::<lambda()>::operator() (__closure=0xb25d28) at /home/tmplt/code/bookwyrm/src/core/plugin_handler.cpp:90
#7  std::__invoke_impl<void, bookwyrm::core::plugin_handler::async_search()::<lambda()> > (__f=...) at /nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/include/c++/7.3.0/bits/invoke.h:60
#8  std::__invoke<bookwyrm::core::plugin_handler::async_search()::<lambda()> > (__fn=...) at /nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/include/c++/7.3.0/bits/invoke.h:95
#9  std::thread::_Invoker<std::tuple<bookwyrm::core::plugin_handler::async_search()::<lambda()> > >::_M_invoke<0> (this=0xb25d28) at /nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/include/c++/7.3.0/thread:234
#10 std::thread::_Invoker<std::tuple<bookwyrm::core::plugin_handler::async_search()::<lambda()> > >::operator() (this=0xb25d28) at /nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/include/c++/7.3.0/thread:243
#11 std::thread::_State_impl<std::thread::_Invoker<std::tuple<bookwyrm::core::plugin_handler::async_search()::<lambda()> > > >::_M_run(void) (this=0xb25d20) at /nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/include/c++/7.3.0/thread:186
#12 0x00007ffff6f3009f in ?? () from /nix/store/4zd34747fz0ggzzasy4icgn3lmy89pra-gcc-7.3.0-lib/lib/libstdc++.so.6
#13 0x00007ffff66ff2a7 in start_thread () from /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libpthread.so.0
#14 0x00007ffff643657f in clone () from /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6
```
